name: webview_flutter_wkwebview
description: A Flutter plugin that provides a WebView widget based on Apple's WKWebView control.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 4.2.0 # original version was 2.7.1 when this was forked

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      ios:
        pluginClass: FLTWebViewFlutterPlugin

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

  flutter:
    sdk: flutter
  # FOR TESTING ONLY. DO NOT MERGE.
  webview_flutter_platform_interface: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^4.1.0

dev_dependencies:
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0
      
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  mplat_pr_tools: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0
  pedantic: ^1.10.0