name: webview_flutter_wkwebview
description: A Flutter plugin that provides a WebView widget based on Apple's WKWebView control.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 5.13.0 # original version was 2.7.1 when this was forked

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      ios:
        pluginClass: FLTWebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_platform_interface: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

dev_dependencies:      
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0