name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 5.12.0 # original version was 2.8.3 when this was forked

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  
  webview_flutter_platform_interface: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
  pigeon: ^3.0.0
