name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 5.2.0 # original version was 3.0.1 when this was forked

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.0.0

  flutter:
    sdk: flutter
  # FOR TESTING ONLY. DO NOT MERGE.
  webview_flutter_android: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

  webview_flutter_platform_interface: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

  webview_flutter_wkwebview: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

# dependency_overrides:
#   alkami_core_dependencies:
#     path: ../../../../flutter_platform/packages/alkami_core_dependencies
#   webview_flutter_android:
#     path: ../webview_flutter_android
#   webview_flutter_platform_interface:
#     path: ../webview_flutter_platform_interface
#   webview_flutter_wkwebview:
#     path: ../webview_flutter_wkwebview

dev_dependencies:
#   alkami_core_dev_dependencies:
#     path: ../../../../flutter_platform/packages/alkami_core_dev_dependencies
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.0.0
  build_runner: ^2.1.5

  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  mockito: ^5.0.16

#   mplat_pr_tools:
#     path: ../../../../mplat_pull_request_tools
  mplat_pr_tools: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^3.0.0

  pedantic: ^1.10.0
