name: webview_flutter_platform_interface
description: A common platform interface for the webview_flutter plugin.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutterpackages/
version: 3.3.0 # original version was 1.8.1 when this was forked

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  mplat_pr_tools:
    git:
      url: https://github.com/Alkami/mplat_pull_request_tools.git
      ref: chore/micaiah/DEV-139004-publish-webview-to-cloudsmith
  pedantic: ^1.10.0
