name: webview_flutter_web
description: A Flutter plugin that provides a WebView widget on web.
repository: https://github.com/Alkami/plugins/tree/main/packages/webview_flutter
publish_to: https://dart.cloudsmith.io/alkami/flutter/
version: 5.12.0 # original version was 0.1.0+1 when this was forked

environment:
  sdk: ">=2.18.0 <3.0.0" # dart version
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  webview_flutter_platform_interface: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.5

  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  mockito: ^5.0.0
