name: Validate Labels

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  build:
    name: Validate PR Labels
    uses: alkami/flutter_platform/.github/workflows/reusable_label_validation.yaml@main
    secrets: inherit
