name: Validate Labels

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - labeled
      - unlabeled

defaults:
  run:
    working-directory: webview_flutter

jobs:
  build:
    name: Validate PR Labels
    uses: alkami/github_actions/.github/workflows/reusable_label_validation.yaml@main
    secrets: inherit
