name: Validate PR

on:
  pull_request:
    branches:
      - main
      - hotfix/**

jobs:
  build:
    name: Validate Pull Request is Ready for Merge
    uses: ./.github/workflows/reusable_pr_validation.yaml
    secrets: inherit
