env:
  FLUTTER_VERSION: 3.7.3
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  # Using the GH_ACTIONS_PAT so that it can bypass branch protection PR requirement
  # Info of how this works: https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-actionv
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}

on:
  workflow_call:

jobs:
  build:
    # *** This if check is very important ***
    # We use this to make sure that we do not get into an infinite loop of workflow runs triggered by a push.
    if: github.event.pusher.name != 'alkami-svc-github-circle'
    name: Publish Package - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup Alkami Environment 
        uses: alkami/github_actions/.github/composites/environment_setup@main

      - name: Publish
        run: ./shell_scripts/alkamiPublish.sh
